apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-food
  namespace: api-food
  labels:
    app: api-food
spec:
  selector:
    matchLabels:
      app: api-food
  template:
    metadata:
      labels:
        app: api-food
    spec:
      containers:
      - name: api-food
        image: eu.gcr.io/khaly-221308/demo-contour
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        env:
        - name: VERSION
          value: "Food"
        - name: TEAM
          value: "Licorne"
        - name: LABEL
          value: "Main"
        - name: ROUTING
          value: "false"
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: api-food
  namespace: api-food
  labels:
    app: api-food
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: api-food
